INSERT INTO public.all_key_skills (name, count) VALUES ('Java EE', 3);
INSERT INTO public.all_key_skills (name, count) VALUES ('Java Servlets', 2);
INSERT INTO public.all_key_skills (name, count) VALUES ('Git', 2);
INSERT INTO public.all_key_skills (name, count) VALUES ('Java', 2);
INSERT INTO public.all_key_skills (name, count) VALUES ('Software Development', 1);
INSERT INTO public.all_key_skills (name, count) VALUES ('Hibernate ORM', 1);
INSERT INTO public.all_key_skills (name, count) VALUES ('UML', 1);
INSERT INTO public.all_key_skills (name, count) VALUES ('ООП', 1);
INSERT INTO public.all_key_skills (name, count) VALUES ('TDD', 1);
INSERT INTO public.all_key_skills (name, count) VALUES ('Apache Tomcat', 1);
INSERT INTO public.all_key_skills (name, count) VALUES ('SQL', 1);
INSERT INTO public.all_key_skills (name, count) VALUES ('Unit Testing', 1);
INSERT INTO public.all_key_skills (name, count) VALUES ('NoSQL', 1);
INSERT INTO public.all_key_skills (name, count) VALUES ('Liferay', 1);
INSERT INTO public.all_key_skills (name, count) VALUES ('Multithread Programming', 1);
INSERT INTO public.all_key_skills (name, count) VALUES ('MS SQL', 1);
INSERT INTO public.all_key_skills (name, count) VALUES ('Atlassian Jira', 1);